# Load records for each chanel.
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH0, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=0")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH0, STDAR_PORT=$(DEVICE_NAME)_ch0_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH1, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=1")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH1, STDAR_PORT=$(DEVICE_NAME)_ch1_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH2, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=2")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH2, STDAR_PORT=$(DEVICE_NAME)_ch2_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH3, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=3")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH3, STDAR_PORT=$(DEVICE_NAME)_ch3_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH4, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=4")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH4, STDAR_PORT=$(DEVICE_NAME)_ch4_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH5, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=5")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH5, STDAR_PORT=$(DEVICE_NAME)_ch5_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH6, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=6")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH6, STDAR_PORT=$(DEVICE_NAME)_ch6_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH7, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=7")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH7, STDAR_PORT=$(DEVICE_NAME)_ch7_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH8, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=8")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH8, STDAR_PORT=$(DEVICE_NAME)_ch8_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH9, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=9")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH9, STDAR_PORT=$(DEVICE_NAME)_ch9_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH10, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=10")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH10, STDAR_PORT=$(DEVICE_NAME)_ch10_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH11, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=11")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH11, STDAR_PORT=$(DEVICE_NAME)_ch11_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH12, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=12")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH12, STDAR_PORT=$(DEVICE_NAME)_ch12_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH13, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=13")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH13, STDAR_PORT=$(DEVICE_NAME)_ch13_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH14, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=14")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH14, STDAR_PORT=$(DEVICE_NAME)_ch14_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH15, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=15")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH15, STDAR_PORT=$(DEVICE_NAME)_ch15_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH16, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=16")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH16, STDAR_PORT=$(DEVICE_NAME)_ch16_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH17, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=17")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH17, STDAR_PORT=$(DEVICE_NAME)_ch17_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH18, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=18")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH18, STDAR_PORT=$(DEVICE_NAME)_ch18_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH19, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=19")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH19, STDAR_PORT=$(DEVICE_NAME)_ch19_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH20, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=20")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH20, STDAR_PORT=$(DEVICE_NAME)_ch20_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH21, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=21")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH21, STDAR_PORT=$(DEVICE_NAME)_ch21_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH22, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=22")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH22, STDAR_PORT=$(DEVICE_NAME)_ch22_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH23, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=23")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH23, STDAR_PORT=$(DEVICE_NAME)_ch23_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH24, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=24")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH24, STDAR_PORT=$(DEVICE_NAME)_ch24_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH25, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=25")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH25, STDAR_PORT=$(DEVICE_NAME)_ch25_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH26, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=26")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH26, STDAR_PORT=$(DEVICE_NAME)_ch26_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH27, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=27")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH27, STDAR_PORT=$(DEVICE_NAME)_ch27_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH28, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=28")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH28, STDAR_PORT=$(DEVICE_NAME)_ch28_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH29, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=29")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH29, STDAR_PORT=$(DEVICE_NAME)_ch29_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH30, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=30")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH30, STDAR_PORT=$(DEVICE_NAME)_ch30_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH31, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=31")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH31, STDAR_PORT=$(DEVICE_NAME)_ch31_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH32, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=32")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH32, STDAR_PORT=$(DEVICE_NAME)_ch32_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH33, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=33")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH33, STDAR_PORT=$(DEVICE_NAME)_ch33_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH34, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=34")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH34, STDAR_PORT=$(DEVICE_NAME)_ch34_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH35, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=35")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH35, STDAR_PORT=$(DEVICE_NAME)_ch35_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH36, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=36")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH36, STDAR_PORT=$(DEVICE_NAME)_ch36_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH37, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=37")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH37, STDAR_PORT=$(DEVICE_NAME)_ch37_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH38, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=38")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH38, STDAR_PORT=$(DEVICE_NAME)_ch38_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH39, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=39")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH39, STDAR_PORT=$(DEVICE_NAME)_ch39_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH40, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=40")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH40, STDAR_PORT=$(DEVICE_NAME)_ch40_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH41, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=41")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH41, STDAR_PORT=$(DEVICE_NAME)_ch41_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH42, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=42")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH42, STDAR_PORT=$(DEVICE_NAME)_ch42_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH43, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=43")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH43, STDAR_PORT=$(DEVICE_NAME)_ch43_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH44, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=44")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH44, STDAR_PORT=$(DEVICE_NAME)_ch44_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH45, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=45")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH45, STDAR_PORT=$(DEVICE_NAME)_ch45_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH46, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=46")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH46, STDAR_PORT=$(DEVICE_NAME)_ch46_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH47, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=47")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH47, STDAR_PORT=$(DEVICE_NAME)_ch47_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH48, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=48")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH48, STDAR_PORT=$(DEVICE_NAME)_ch48_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH49, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=49")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH49, STDAR_PORT=$(DEVICE_NAME)_ch49_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH50, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=50")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH50, STDAR_PORT=$(DEVICE_NAME)_ch50_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH51, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=51")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH51, STDAR_PORT=$(DEVICE_NAME)_ch51_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH52, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=52")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH52, STDAR_PORT=$(DEVICE_NAME)_ch52_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH53, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=53")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH53, STDAR_PORT=$(DEVICE_NAME)_ch53_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH54, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=54")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH54, STDAR_PORT=$(DEVICE_NAME)_ch54_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH55, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=55")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH55, STDAR_PORT=$(DEVICE_NAME)_ch55_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH56, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=56")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH56, STDAR_PORT=$(DEVICE_NAME)_ch56_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH57, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=57")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH57, STDAR_PORT=$(DEVICE_NAME)_ch57_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH58, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=58")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH58, STDAR_PORT=$(DEVICE_NAME)_ch58_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH59, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=59")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH59, STDAR_PORT=$(DEVICE_NAME)_ch59_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH60, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=60")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH60, STDAR_PORT=$(DEVICE_NAME)_ch60_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH61, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=61")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH61, STDAR_PORT=$(DEVICE_NAME)_ch61_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH62, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=62")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH62, STDAR_PORT=$(DEVICE_NAME)_ch62_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
dbLoadRecords("$(TR_CORE)/db/TRChannel.db", "PREFIX=$(PREFIX):CH63, CHANNELS_PORT=$(DEVICE_NAME)_channels, CHANNEL=63")
dbLoadRecords("$(TR_CORE)/db/TRChannelData.db", "PREFIX=$(PREFIX):CH63, STDAR_PORT=$(DEVICE_NAME)_ch63_stdarrays, SIZE=$(WAVEFORM_SIZE), SNAP_SCAN=$(SNAP_SCAN)")
